networks:
  sbc_network:
    name: sbc_network

volumes:
  sbc_redis_data:
    name: sbc_redis_data

services:
  sbc-postgres:
    container_name: sbc-postgres
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=sbc_db
    volumes:
      - type: tmpfs
        target: /data/db
    networks:
      - sbc_network

  sbc-pgadmin:
    container_name: sbc-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@maksympanov.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "5050:80"
    depends_on:
      - sbc-postgres